# -*- coding: utf-8 -*-
"""Actividad_6+FacundoVillalba

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16NUK0xITrO8Al5wRev6vRFcHcjpJTYXL
"""

'''
Actividad N°6 Cuenta
Crea una clase llamada Cuenta que tendrá los siguientes atributos: titular (que es una persona) y cantidad (puede tener 
decimales). El titular será obligatorio y la cantidad es opcional. Construye los siguientes métodos para la clase: 
Un constructor.
mostrar(): Muestra los datos de la cuenta. 
 ingresar(cantidad): se ingresa una cantidad a la cuenta, si la cantidad introducida es negativa, no se hará nada. 
retirar(cantidad): se retira una cantidad a la cuenta. La cuenta puede estar en números rojos
'''
class Cuenta:
    def __init__(self, titular, cantidad):
        self.titular = titular
        self.cantidad = cantidad      
    
    def mostrar(self):
        print(f"Datos de Cuenta\nTitular: {titular.apellido} {titular.nombre} Saldo ${cuenta.cantidad}")
       
    def ingresar(self, cantidad):
        if (cantidad > 0):
            self.cantidad = cuenta.cantidad + cantidad
        print(f"Ingreso: {cantidad} Saldo ${cuenta.cantidad}")    
    
    def retirar(self, cantidad):
        if (cantidad < 0):
            self.cantidad = cuenta.cantidad + cantidad
        print(f"Retiro: {cantidad} Saldo ${cuenta.cantidad}")  

class Titular:
    def __init__(self, nombre, apellido):
        self.nombre = nombre
        self.apellido = apellido 
      
titular = Titular("Facundo", "Villalba")  
cuenta = Cuenta(titular, 15000)

cuenta.mostrar()
cuenta.ingresar(5000)
cuenta.ingresar(-500)
cuenta.retirar(-2000)
cuenta.retirar(2000)
cuenta.retirar(-20000)